# Generated by Django 6.0.4 on 2026-04-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_transactionintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('HCS', 'HCS'), ('HOD', 'HOD'), ('HOU', 'HOU'), ('STAFF', 'Staff'), ('SELLER', 'Seller')], default='STAFF', max_length=20),
        ),
    ]
