# Generated by Django 6.0.4 on 2026-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_user_seller_alias_user_seller_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
