# Generated by Django 6.0.4 on 2026-04-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_user_seller_id_user_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
